# GitHub Pages 配置文件
# 用于配置Jekyll和GitHub Pages的基本设置

# 网站基本信息
title: "EDMG - Enhanced Dynamic Motion Generation"
description: "EDMG项目官方主页 - 创新的动态运动生成研究"
author: "zjm77k"
email: ""
url: "https://zjm77k.github.io"
baseurl: ""

# 社交媒体链接
github_username: zjm77k
twitter_username: ""
linkedin_username: ""

# 网站设置
timezone: Asia/Shanghai
lang: zh-CN
encoding: utf-8

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# 包含文件
include:
  - _pages

# 集合设置
collections:
  pages:
    output: true
    permalink: /:name/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# SEO设置
google_analytics: ""
google_site_verification: ""

# 社交媒体设置
social:
  name: neymar277
  links:
    - https://github.com/neymar277

# 网站图标
favicon: "/favicon.ico"

# 主题设置（如果使用Jekyll主题）
theme: minima

# 自定义变量
edmg:
  version: "1.0.0"
  release_date: "2024-01-01"
  paper_url: "./EDMG_5191 (13).pdf"
  github_repo: "https://github.com/neymar277/EDMG"
  demo_video: "./EDMG.mp4"
